#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_TEAM_ID "22"
#define APP_TEAM_NAME "CIRCUIT_VOYAGE"

#define APP_LINE_SPEED_MM_S 500
#define APP_MARKER_MIN_DISTANCE_MM 250
#define APP_MARKER_BLACK_COUNT 42

#define APP_GATE_MIN_CM 15
#define APP_GATE_MAX_CM 90
#define APP_GATE_MIN_SCORE 25
#define APP_GATE_ENTER_STABLE_MS 120
#define APP_GATE_EXIT_STABLE_MS 150
#define APP_GATE_LOCK_DISTANCE_MM 300
#define APP_GATE_LOCK_MS 1200
#define APP_GATE_EXIT_JUMP_CM 30

#define APP_RADAR_SCAN_YAW 1800
#define APP_RADAR_SCAN_MS 800
#define APP_AVOID_SPEED_MM_S 350
#define APP_AVOID_YAW 1600
#define APP_AVOID_MS 1600

#define APP_DISPLAY_PERIOD_MS 100
#define APP_STATE_PERIOD_MS 50

#endif
