#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_TEAM_ID "00"
#define APP_TEAM_NAME "TRACK_LINE_CAR"
#define APP_CURRENT_TIME "00:00"

#define APP_LINE_SPEED_MM_S 500
#define APP_MARKER_MIN_DISTANCE_MM 250
#define APP_MARKER_BLACK_COUNT 42

#define APP_RADAR_SCAN_YAW 1800
#define APP_RADAR_SCAN_MS 800
#define APP_AVOID_SPEED_MM_S 350
#define APP_AVOID_YAW 1600
#define APP_AVOID_MS 1600

#define APP_DISPLAY_PERIOD_MS 100
#define APP_STATE_PERIOD_MS 50

#endif
