#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_TEAM_ID "22"
#define APP_TEAM_NAME "CIRCUIT_VOYAGE"

#define APP_LINE_SPEED_MM_S 320
#define APP_LINE_MIN_SPEED_MM_S 180
#define APP_LINE_SLOW_OFFSET 18
#define APP_LINE_SLOWDOWN_MM_S_PER_PIXEL 6
#define APP_LINE_SPEED_STEP_MM_S 30
#define APP_LINE_LOOP_SPEED_MM_S 220
#define APP_LINE_EXIT_SPEED_MM_S 180
#define APP_TRACK_BRANCH_LOCK_MM 500
#define APP_TRACK_SQUARE_ZONE_START_MM 2200
#define APP_TRACK_SQUARE_ZONE_END_MM 4700
#define APP_TRACK_SQUARE_MIN_EXIT_MM 1500
#define APP_TRACK_SQUARE_FORCE_EXIT_MM 2200
#define APP_TRACK_CIRCLE_ZONE_START_MM 4700
#define APP_TRACK_CIRCLE_ZONE_END_MM 6900
#define APP_TRACK_CIRCLE_MIN_EXIT_MM 1100
#define APP_TRACK_CIRCLE_FORCE_EXIT_MM 1800
#define APP_TRACK_EXIT_SEGMENT_RIGHT 1
#define APP_MARKER_MIN_DISTANCE_MM 250
#define APP_MARKER_BLACK_COUNT 42
#define APP_OPENMV_TIMEOUT_MS 150
#define APP_OPENMV_LOST_HOLD_TICKS 3
#define APP_OPENMV_SEARCH_TICKS 45
#define APP_OPENMV_SEARCH_SPEED_MM_S 120
#define APP_OPENMV_SEARCH_YAW 900
#define APP_OPENMV_ROUTE_LOCK_MS 700

#define APP_GATE_MIN_CM 15
#define APP_GATE_MAX_CM 90
#define APP_GATE_MIN_SCORE 25
#define APP_GATE_ENTER_STABLE_MS 120
#define APP_GATE_EXIT_STABLE_MS 150
#define APP_GATE_LOCK_DISTANCE_MM 300
#define APP_GATE_LOCK_MS 1200
#define APP_GATE_EXIT_JUMP_CM 30

#define APP_RADAR_SCAN_YAW 1800
#define APP_RADAR_SCAN_MS 800
#define APP_AVOID_SPEED_MM_S 350
#define APP_AVOID_YAW 1600
#define APP_AVOID_MS 1600

#define APP_DISPLAY_PERIOD_MS 100
#define APP_STATE_PERIOD_MS 50

#endif
